### ISSUE TITLE
Obsolete version of CodeMirror?

### ISSUE THREAD

**Issue by jglick** [stapler/stapler-adjunct-codemirror#1]
Would like to use http://codemirror.net/mode/groovy/ from `lib/hudson/scriptConsole.jelly` but this seems impossible using the currently packaged version. Should be updated and published.

**Comment by jglick** [comment]
`shell` mode would also be useful in `hudson.tasks.Shell` and the like.

**Comment by jglick** [comment]
Also: [JENKINS-16359](https://issues.jenkins-ci.org/browse/JENKINS-16359)

**Comment by kohsuke** [comment]
integrated v2.38 from upstream, which is the latest version in the v2 line.

**Comment by jglick** [comment]
Does not seem to have helped [JENKINS-15604](https://issues.jenkins-ci.org/browse/JENKINS-15604).
